# Generated by Django 5.2.4 on 2025-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuariointerno_impresora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('licencia', models.CharField(blank=True, max_length=100, null=True)),
                ('es_base', models.BooleanField(default=False)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='softwares', to='usuarios.usuariointerno')),
            ],
        ),
    ]
