# Generated by Django 5.2.4 on 2025-07-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_remove_software_licencia_remove_software_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='es_base',
        ),
    ]
