# Generated by Django 5.2.4 on 2025-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PC', 'Ordenador'), ('MONITOR', 'Monitor'), ('IMPRESORA', 'Impresora'), ('ROUTER', 'Router'), ('OTRO', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('en_uso', models.BooleanField(default=True)),
            ],
        ),
    ]
