# Generated by Django 5.2.4 on 2025-07-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_TI', '0002_impresora_impresoraetiquetas_monitor_otro_pc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='pc_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores', to='equipos_TI.pc'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='portatil_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores', to='equipos_TI.portatil'),
        ),
        migrations.AddField(
            model_name='raton',
            name='pc_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratones', to='equipos_TI.pc'),
        ),
        migrations.AddField(
            model_name='raton',
            name='portatil_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratones', to='equipos_TI.portatil'),
        ),
        migrations.AddField(
            model_name='teclado',
            name='pc_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teclados', to='equipos_TI.pc'),
        ),
        migrations.AddField(
            model_name='teclado',
            name='portatil_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teclados', to='equipos_TI.portatil'),
        ),
    ]
