# Generated by Django 5.2.4 on 2025-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_TI', '0003_monitor_pc_asociado_monitor_portatil_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='impresoraetiquetas',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='monitor',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='otro',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='pc',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='portatil',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='raton',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='switch',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='teclado',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado a un usuario/equipo'), ('almacen_uso', 'En almacén para usar'), ('almacen_devolucion', 'En almacén para devolver')], default='almacen_uso', max_length=20),
        ),
    ]
