# Generated by Django 5.2.4 on 2025-07-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_TI', '0004_impresora_estado_impresoraetiquetas_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='impresoraetiquetas',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='otro',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='pc',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='portatil',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='raton',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='router',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
        migrations.AddField(
            model_name='teclado',
            name='ubicacion',
            field=models.CharField(choices=[('almacen_n1', 'Almacén N1'), ('almacen_n2', 'Almacén N2'), ('verificacion_n1', 'Verificación N1'), ('verificacion_n2', 'Verificación N2'), ('archivo', 'Archivo'), ('taller', 'Taller')], default='archivo', max_length=50),
        ),
    ]
